### ISSUE TITLE
发送交易，签名失效

### ISSUE THREAD

**Issue by LyyDandelion** [xuehongyang/FilecoinJ#2]
地址创建，秘钥类型是：secp256k1，发送交易时，生成的秘钥格式例如（fTeCO1/I76rrLg5WfPOMcpi1WPTrqnj8=）无法签名：
错误信息：
```
`java.lang.RuntimeException: Illegal hexadecimal character u at index 0
	at cn.hutool.core.util.HexUtil.toDigit(HexUtil.java:398)
	at cn.hutool.core.util.HexUtil.decodeHex(HexUtil.java:182)
	at cn.hutool.core.util.HexUtil.decodeHex(HexUtil.java:203)
	at com.filecoinj.handler.FilecoinHandler.send(FilecoinHandler.java:194)`
```

**Comment by xuehongyang** [comment]
不好意思，春节期间休息没留意信息。
